disabled_rules:
  - file_length
  - function_parameter_count
  - function_body_length
  - large_tuple
  - nesting
  - todo
  - type_body_length
  - xctfail_message

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - empty_string
  - explicit_init
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - trailing_closure
  - vertical_parameter_alignment_on_call

excluded:
  - .git/
  - Carthage/
  - Pods/
  - XpringKit/**/Generated/*

# Use indentation equal to two spaces.
indentation_width:
  indentation_width: 2
