# Specification for XpringKit's XCode project.
name: XpringKit
options:
  bundleIdPrefix: io.xpring
targets:
  XpringKit:
    type: framework
    platform: iOS
    sources: [XpringKit]
    resources: [XpringKit/Resources]
    scheme:
      testTargets:
        - XpringKitTests
      gatherCoverageData: true
    preBuildScripts:
      - script: ./scripts/bundle_js.sh
        name: Bundle JS
    postCompileScripts:
      - script: swiftlint autocorrect --config .swiftlint.yml
        name: SwiftLint
  XpringKitTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: XpringKit
