# Specification for XpringKit's XCode project.
name: XpringKit
options:
  bundleIdPrefix: io.xpring
  deploymentTarget:
    iOS: 11.0
    macOS: 10.13
settings:
  LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks $(PROJECT_DIR)/Carthage/Build/iOS"
targets:
  XpringKit:
    type: framework
    platform: [iOS, macOS]
    sources:  
      - path: XpringKit
        excludes:
          - "**/.swiftlint.yml"
    resources: [XpringKit/Common/Resources]
    scheme:
      testTargets:
        - XpringKitTests_${platform}
      gatherCoverageData: true
    postCompileScripts:
      - name: SwiftLint
        script: |
          if which swiftlint >/dev/null; then
            # Autocorrect anything SwiftLint can solve, then lint.
            swiftlint autocorrect
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
    dependencies:
      - carthage: BigInt
      - carthage: SwiftProtobuf
      - carthage: SwiftGRPC
  XpringKitTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources: [Tests]
    dependencies:
      - target: XpringKit_${platform}
