//
// Receipt.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Receipt: Codable {

    public var invoiceHash: String
    public var transactionConfirmation: String

    public init(invoiceHash: String, transactionConfirmation: String) {
        self.invoiceHash = invoiceHash
        self.transactionConfirmation = transactionConfirmation
    }


}

