//
// TravelRule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct TravelRule: Codable {

    public var originator: Originator
    public var beneficiary: Beneficiary

    public init(originator: Originator, beneficiary: Beneficiary) {
        self.originator = originator
        self.beneficiary = beneficiary
    }

}
