/// Conforms Org_Interledger_Stream_Proto_IlpOverHttpServiceServiceClient to IlpNetworkPaymentClient
extension Org_Interledger_Stream_Proto_IlpOverHttpServiceServiceClient: IlpNetworkPaymentClient {

}
