/// Conforms Org_Interledger_Stream_Proto_BalanceServiceServiceClient to IlpNetworkBalanceClient
extension Org_Interledger_Stream_Proto_BalanceServiceServiceClient: IlpNetworkBalanceClient {}
extension Org_Interledger_Stream_Proto_BalanceServiceServiceClient: ILPNetworkBalanceClient {}
